FROM php:8.1-fpm

RUN apt-get update && apt-get install \
    zlib1g libzip-dev -y \
    && apt-get install -y --no-install-recommends ssh \
    && docker-php-ext-install pdo_mysql zip

RUN pecl install xdebug
RUN docker-php-ext-enable xdebug

RUN echo "xdebug.coverage_enable" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.mode=coverage" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
